### PR TITLE
Assembly actions for M198 Howitzer

### PR DESCRIPTION
**Pull request by Grey-Soldierman**
This PR will enable you to: 
Attach, Detach and Store the feet on the M198 Howitzer.
Attach and Detach the Jack handles on the M198 Howitzer.
Raise and Lower the shackles for slingloading on the M198 Howitzer. 

Known Issues:
Binarize gives a popup error when packing. It is related to the conditions of the ACE actions i have added.  There is no clear error message in the logs or through make when packing, just a general error message from Binarize.exe.

### CODE REVIEW

**Comment by PabstMirror** [comment]
Arrays in `QUOTE` macros can be a real pain because each sub-array also needs the `ARR_X` macros:
You end up with stuff like 

```
statement = QUOTE([ARR_4(_target,_player,[ARR_4([ARR_2('move_left_foot',0)],[ARR_2('rotate_left_foot',0)],[ARR_2('rotate_left_foot_2',0)],[ARR_2('hide_left_foot',1)])],'ACE_M198_Foot_F')] call FUNC(detachPart));
```

I made the changes you would need here: https://github.com/acemod/ACEX_artillery/commit/9ef40535633de553ba36ff37efa58d00d8aadd94

**Comment by Grey-Soldierman** [comment]
Thats brilliant, cheers for the help. Is there a more efficient way i could implement it then or just something we'd have to deal with ?

**Comment by PabstMirror** [comment]
I don't think there is a "best" way to do it, if it works then it's fine.
I like to move as much as I can to the sqf file. e..g

```
class ACE_Foot_Detach_L {
    condition = QUOTE([ARR_3(_target,_player,'ACE_Foot_Detach_L')] call FUNC(canDetachPart));
    statement = QUOTE([ARR_3(_target,_player,'ACE_Foot_Detach_L')] call FUNC(detachPart));
};

// sqf:
params ["_target", "_player", "_action"];

swtich (_action) do {
   case ("ACE_Foot_Detach_L"): {
        //code
    };
};
```

But I wouldn't change what you have.

**Comment by SGTGunner** [comment]
@PabstMirror Is this PR going to ever get merged? I like the changes.

**Pull request merged**
